// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InnerMessage.proto

package com.whollyframework.protobuf.model;

public final class InnerMessageProtos {
  private InnerMessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface InnerMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.whollyframework.protobuf.InnerMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string name = 1 [default = "name"];</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 1 [default = "name"];</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 1 [default = "name"];</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional int32 id = 2;</code>
     */
    boolean hasId();
    /**
     * <code>optional int32 id = 2;</code>
     */
    int getId();

    /**
     * <code>optional .com.whollyframework.protobuf.EnumType type = 3 [default = UNIVERSAL];</code>
     */
    boolean hasType();
    /**
     * <code>optional .com.whollyframework.protobuf.EnumType type = 3 [default = UNIVERSAL];</code>
     */
    com.whollyframework.protobuf.model.EnumTypeProtos.EnumType getType();
  }
  /**
   * Protobuf type {@code com.whollyframework.protobuf.InnerMessage}
   */
  public static final class InnerMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.whollyframework.protobuf.InnerMessage)
      InnerMessageOrBuilder {
    // Use InnerMessage.newBuilder() to construct.
    private InnerMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private InnerMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final InnerMessage defaultInstance;
    public static InnerMessage getDefaultInstance() {
      return defaultInstance;
    }

    public InnerMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private InnerMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              id_ = input.readInt32();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              com.whollyframework.protobuf.model.EnumTypeProtos.EnumType value = com.whollyframework.protobuf.model.EnumTypeProtos.EnumType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                type_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.whollyframework.protobuf.model.InnerMessageProtos.internal_static_com_whollyframework_protobuf_InnerMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.whollyframework.protobuf.model.InnerMessageProtos.internal_static_com_whollyframework_protobuf_InnerMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessage.class, com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<InnerMessage> PARSER =
        new com.google.protobuf.AbstractParser<InnerMessage>() {
      public InnerMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InnerMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<InnerMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 1 [default = "name"];</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string name = 1 [default = "name"];</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 1 [default = "name"];</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <code>optional int32 id = 2;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 id = 2;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private com.whollyframework.protobuf.model.EnumTypeProtos.EnumType type_;
    /**
     * <code>optional .com.whollyframework.protobuf.EnumType type = 3 [default = UNIVERSAL];</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .com.whollyframework.protobuf.EnumType type = 3 [default = UNIVERSAL];</code>
     */
    public com.whollyframework.protobuf.model.EnumTypeProtos.EnumType getType() {
      return type_;
    }

    private void initFields() {
      name_ = "name";
      id_ = 0;
      type_ = com.whollyframework.protobuf.model.EnumTypeProtos.EnumType.UNIVERSAL;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, type_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, type_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.whollyframework.protobuf.InnerMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.whollyframework.protobuf.InnerMessage)
        com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.whollyframework.protobuf.model.InnerMessageProtos.internal_static_com_whollyframework_protobuf_InnerMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.whollyframework.protobuf.model.InnerMessageProtos.internal_static_com_whollyframework_protobuf_InnerMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessage.class, com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessage.Builder.class);
      }

      // Construct using com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "name";
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = com.whollyframework.protobuf.model.EnumTypeProtos.EnumType.UNIVERSAL;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.whollyframework.protobuf.model.InnerMessageProtos.internal_static_com_whollyframework_protobuf_InnerMessage_descriptor;
      }

      public com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessage getDefaultInstanceForType() {
        return com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessage.getDefaultInstance();
      }

      public com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessage build() {
        com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessage buildPartial() {
        com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessage result = new com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessage) {
          return mergeFrom((com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessage other) {
        if (other == com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessage.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "name";
      /**
       * <code>optional string name = 1 [default = "name"];</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string name = 1 [default = "name"];</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 1 [default = "name"];</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1 [default = "name"];</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1 [default = "name"];</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1 [default = "name"];</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private int id_ ;
      /**
       * <code>optional int32 id = 2;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 id = 2;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 2;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 2;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        onChanged();
        return this;
      }

      private com.whollyframework.protobuf.model.EnumTypeProtos.EnumType type_ = com.whollyframework.protobuf.model.EnumTypeProtos.EnumType.UNIVERSAL;
      /**
       * <code>optional .com.whollyframework.protobuf.EnumType type = 3 [default = UNIVERSAL];</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .com.whollyframework.protobuf.EnumType type = 3 [default = UNIVERSAL];</code>
       */
      public com.whollyframework.protobuf.model.EnumTypeProtos.EnumType getType() {
        return type_;
      }
      /**
       * <code>optional .com.whollyframework.protobuf.EnumType type = 3 [default = UNIVERSAL];</code>
       */
      public Builder setType(com.whollyframework.protobuf.model.EnumTypeProtos.EnumType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.whollyframework.protobuf.EnumType type = 3 [default = UNIVERSAL];</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = com.whollyframework.protobuf.model.EnumTypeProtos.EnumType.UNIVERSAL;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.whollyframework.protobuf.InnerMessage)
    }

    static {
      defaultInstance = new InnerMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.whollyframework.protobuf.InnerMessage)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_whollyframework_protobuf_InnerMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_whollyframework_protobuf_InnerMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022InnerMessage.proto\022\034com.whollyframewor" +
      "k.protobuf\032\016EnumType.proto\"o\n\014InnerMessa" +
      "ge\022\022\n\004name\030\001 \001(\t:\004name\022\n\n\002id\030\002 \001(\005\022?\n\004ty" +
      "pe\030\003 \001(\0162&.com.whollyframework.protobuf." +
      "EnumType:\tUNIVERSALB8\n\"com.whollyframewo" +
      "rk.protobuf.modelB\022InnerMessageProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.whollyframework.protobuf.model.EnumTypeProtos.getDescriptor(),
        }, assigner);
    internal_static_com_whollyframework_protobuf_InnerMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_whollyframework_protobuf_InnerMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_whollyframework_protobuf_InnerMessage_descriptor,
        new java.lang.String[] { "Name", "Id", "Type", });
    com.whollyframework.protobuf.model.EnumTypeProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
