// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package com.whollyframework.protobuf.model;

import com.google.protobuf.ByteString;
import com.whollyframework.protobuf.pojo.MessagePojo;


public final class MessageProtos {
  private MessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.whollyframework.protobuf.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string strObj = 1 [default = "hello"];</code>
     */
    boolean hasStrObj();
    /**
     * <code>required string strObj = 1 [default = "hello"];</code>
     */
    java.lang.String getStrObj();
    /**
     * <code>required string strObj = 1 [default = "hello"];</code>
     */
    com.google.protobuf.ByteString
        getStrObjBytes();

    /**
     * <code>optional int32 int32Obj = 2;</code>
     */
    boolean hasInt32Obj();
    /**
     * <code>optional int32 int32Obj = 2;</code>
     */
    int getInt32Obj();

    /**
     * <code>optional int64 int64Obj = 3;</code>
     */
    boolean hasInt64Obj();
    /**
     * <code>optional int64 int64Obj = 3;</code>
     */
    long getInt64Obj();

    /**
     * <code>optional uint32 uint32Obj = 4;</code>
     */
    boolean hasUint32Obj();
    /**
     * <code>optional uint32 uint32Obj = 4;</code>
     */
    int getUint32Obj();

    /**
     * <code>optional uint64 uint64Obj = 5;</code>
     */
    boolean hasUint64Obj();
    /**
     * <code>optional uint64 uint64Obj = 5;</code>
     */
    long getUint64Obj();

    /**
     * <code>optional sint32 sint32Obj = 6;</code>
     */
    boolean hasSint32Obj();
    /**
     * <code>optional sint32 sint32Obj = 6;</code>
     */
    int getSint32Obj();

    /**
     * <code>optional sint64 sint64Obj = 7;</code>
     */
    boolean hasSint64Obj();
    /**
     * <code>optional sint64 sint64Obj = 7;</code>
     */
    long getSint64Obj();

    /**
     * <code>optional fixed32 fixed32Obj = 8;</code>
     */
    boolean hasFixed32Obj();
    /**
     * <code>optional fixed32 fixed32Obj = 8;</code>
     */
    int getFixed32Obj();

    /**
     * <code>optional fixed64 fixed64Obj = 9;</code>
     */
    boolean hasFixed64Obj();
    /**
     * <code>optional fixed64 fixed64Obj = 9;</code>
     */
    long getFixed64Obj();

    /**
     * <code>optional sfixed32 sfixed32Obj = 10;</code>
     */
    boolean hasSfixed32Obj();
    /**
     * <code>optional sfixed32 sfixed32Obj = 10;</code>
     */
    int getSfixed32Obj();

    /**
     * <code>optional sfixed64 sfixed64Obj = 11;</code>
     */
    boolean hasSfixed64Obj();
    /**
     * <code>optional sfixed64 sfixed64Obj = 11;</code>
     */
    long getSfixed64Obj();

    /**
     * <code>optional bool boolObj = 12;</code>
     */
    boolean hasBoolObj();
    /**
     * <code>optional bool boolObj = 12;</code>
     */
    boolean getBoolObj();

    /**
     * <code>optional bytes bytesObj = 13;</code>
     */
    boolean hasBytesObj();
    /**
     * <code>optional bytes bytesObj = 13;</code>
     */
    com.google.protobuf.ByteString getBytesObj();

    /**
     * <code>optional float folatObj = 14 [deprecated = true];</code>
     */
    @java.lang.Deprecated boolean hasFolatObj();
    /**
     * <code>optional float folatObj = 14 [deprecated = true];</code>
     */
    @java.lang.Deprecated float getFolatObj();

    /**
     * <code>repeated double doubleObj = 15 [packed = true];</code>
     *
     * <pre>
     * </pre>
     */
    java.util.List<java.lang.Double> getDoubleObjList();
    /**
     * <code>repeated double doubleObj = 15 [packed = true];</code>
     *
     * <pre>
     * </pre>
     */
    int getDoubleObjCount();
    /**
     * <code>repeated double doubleObj = 15 [packed = true];</code>
     *
     * <pre>
     * </pre>
     */
    double getDoubleObj(int index);

    /**
     * <code>optional .com.whollyframework.protobuf.InnerMessage innerMessage = 16;</code>
     */
    boolean hasInnerMessage();
    /**
     * <code>optional .com.whollyframework.protobuf.InnerMessage innerMessage = 16;</code>
     */
    com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessage getInnerMessage();
    /**
     * <code>optional .com.whollyframework.protobuf.InnerMessage innerMessage = 16;</code>
     */
    com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessageOrBuilder getInnerMessageOrBuilder();
  }
  /**
   * Protobuf type {@code com.whollyframework.protobuf.Message}
   */
  public static final class Message extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.whollyframework.protobuf.Message)
      MessageOrBuilder {
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Message(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Message defaultInstance;
    public static Message getDefaultInstance() {
      return defaultInstance;
    }

    public Message getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              strObj_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              int32Obj_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              int64Obj_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              uint32Obj_ = input.readUInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              uint64Obj_ = input.readUInt64();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              sint32Obj_ = input.readSInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              sint64Obj_ = input.readSInt64();
              break;
            }
            case 69: {
              bitField0_ |= 0x00000080;
              fixed32Obj_ = input.readFixed32();
              break;
            }
            case 73: {
              bitField0_ |= 0x00000100;
              fixed64Obj_ = input.readFixed64();
              break;
            }
            case 85: {
              bitField0_ |= 0x00000200;
              sfixed32Obj_ = input.readSFixed32();
              break;
            }
            case 89: {
              bitField0_ |= 0x00000400;
              sfixed64Obj_ = input.readSFixed64();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              boolObj_ = input.readBool();
              break;
            }
            case 106: {
              bitField0_ |= 0x00001000;
              bytesObj_ = input.readBytes();
              break;
            }
            case 117: {
              bitField0_ |= 0x00002000;
              folatObj_ = input.readFloat();
              break;
            }
            case 121: {
              if (!((mutable_bitField0_ & 0x00004000) == 0x00004000)) {
                doubleObj_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00004000;
              }
              doubleObj_.add(input.readDouble());
              break;
            }
            case 122: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00004000) == 0x00004000) && input.getBytesUntilLimit() > 0) {
                doubleObj_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00004000;
              }
              while (input.getBytesUntilLimit() > 0) {
                doubleObj_.add(input.readDouble());
              }
              input.popLimit(limit);
              break;
            }
            case 130: {
              com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessage.Builder subBuilder = null;
              if (((bitField0_ & 0x00004000) == 0x00004000)) {
                subBuilder = innerMessage_.toBuilder();
              }
              innerMessage_ = input.readMessage(com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessage.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(innerMessage_);
                innerMessage_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00004000;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00004000) == 0x00004000)) {
          doubleObj_ = java.util.Collections.unmodifiableList(doubleObj_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.whollyframework.protobuf.model.MessageProtos.internal_static_com_whollyframework_protobuf_Message_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.whollyframework.protobuf.model.MessageProtos.internal_static_com_whollyframework_protobuf_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.whollyframework.protobuf.model.MessageProtos.Message.class, com.whollyframework.protobuf.model.MessageProtos.Message.Builder.class);
    }

    public static com.google.protobuf.Parser<Message> PARSER =
        new com.google.protobuf.AbstractParser<Message>() {
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int STROBJ_FIELD_NUMBER = 1;
    private java.lang.Object strObj_;
    /**
     * <code>required string strObj = 1 [default = "hello"];</code>
     */
    public boolean hasStrObj() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string strObj = 1 [default = "hello"];</code>
     */
    public java.lang.String getStrObj() {
      java.lang.Object ref = strObj_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          strObj_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string strObj = 1 [default = "hello"];</code>
     */
    public com.google.protobuf.ByteString
        getStrObjBytes() {
      java.lang.Object ref = strObj_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        strObj_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INT32OBJ_FIELD_NUMBER = 2;
    private int int32Obj_;
    /**
     * <code>optional int32 int32Obj = 2;</code>
     */
    public boolean hasInt32Obj() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 int32Obj = 2;</code>
     */
    public int getInt32Obj() {
      return int32Obj_;
    }

    public static final int INT64OBJ_FIELD_NUMBER = 3;
    private long int64Obj_;
    /**
     * <code>optional int64 int64Obj = 3;</code>
     */
    public boolean hasInt64Obj() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 int64Obj = 3;</code>
     */
    public long getInt64Obj() {
      return int64Obj_;
    }

    public static final int UINT32OBJ_FIELD_NUMBER = 4;
    private int uint32Obj_;
    /**
     * <code>optional uint32 uint32Obj = 4;</code>
     */
    public boolean hasUint32Obj() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional uint32 uint32Obj = 4;</code>
     */
    public int getUint32Obj() {
      return uint32Obj_;
    }

    public static final int UINT64OBJ_FIELD_NUMBER = 5;
    private long uint64Obj_;
    /**
     * <code>optional uint64 uint64Obj = 5;</code>
     */
    public boolean hasUint64Obj() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional uint64 uint64Obj = 5;</code>
     */
    public long getUint64Obj() {
      return uint64Obj_;
    }

    public static final int SINT32OBJ_FIELD_NUMBER = 6;
    private int sint32Obj_;
    /**
     * <code>optional sint32 sint32Obj = 6;</code>
     */
    public boolean hasSint32Obj() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional sint32 sint32Obj = 6;</code>
     */
    public int getSint32Obj() {
      return sint32Obj_;
    }

    public static final int SINT64OBJ_FIELD_NUMBER = 7;
    private long sint64Obj_;
    /**
     * <code>optional sint64 sint64Obj = 7;</code>
     */
    public boolean hasSint64Obj() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional sint64 sint64Obj = 7;</code>
     */
    public long getSint64Obj() {
      return sint64Obj_;
    }

    public static final int FIXED32OBJ_FIELD_NUMBER = 8;
    private int fixed32Obj_;
    /**
     * <code>optional fixed32 fixed32Obj = 8;</code>
     */
    public boolean hasFixed32Obj() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional fixed32 fixed32Obj = 8;</code>
     */
    public int getFixed32Obj() {
      return fixed32Obj_;
    }

    public static final int FIXED64OBJ_FIELD_NUMBER = 9;
    private long fixed64Obj_;
    /**
     * <code>optional fixed64 fixed64Obj = 9;</code>
     */
    public boolean hasFixed64Obj() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional fixed64 fixed64Obj = 9;</code>
     */
    public long getFixed64Obj() {
      return fixed64Obj_;
    }

    public static final int SFIXED32OBJ_FIELD_NUMBER = 10;
    private int sfixed32Obj_;
    /**
     * <code>optional sfixed32 sfixed32Obj = 10;</code>
     */
    public boolean hasSfixed32Obj() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional sfixed32 sfixed32Obj = 10;</code>
     */
    public int getSfixed32Obj() {
      return sfixed32Obj_;
    }

    public static final int SFIXED64OBJ_FIELD_NUMBER = 11;
    private long sfixed64Obj_;
    /**
     * <code>optional sfixed64 sfixed64Obj = 11;</code>
     */
    public boolean hasSfixed64Obj() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional sfixed64 sfixed64Obj = 11;</code>
     */
    public long getSfixed64Obj() {
      return sfixed64Obj_;
    }

    public static final int BOOLOBJ_FIELD_NUMBER = 12;
    private boolean boolObj_;
    /**
     * <code>optional bool boolObj = 12;</code>
     */
    public boolean hasBoolObj() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional bool boolObj = 12;</code>
     */
    public boolean getBoolObj() {
      return boolObj_;
    }

    public static final int BYTESOBJ_FIELD_NUMBER = 13;
    private com.google.protobuf.ByteString bytesObj_;
    /**
     * <code>optional bytes bytesObj = 13;</code>
     */
    public boolean hasBytesObj() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>optional bytes bytesObj = 13;</code>
     */
    public com.google.protobuf.ByteString getBytesObj() {
      return bytesObj_;
    }

    public static final int FOLATOBJ_FIELD_NUMBER = 14;
    private float folatObj_;
    /**
     * <code>optional float folatObj = 14 [deprecated = true];</code>
     */
    @java.lang.Deprecated public boolean hasFolatObj() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <code>optional float folatObj = 14 [deprecated = true];</code>
     */
    @java.lang.Deprecated public float getFolatObj() {
      return folatObj_;
    }

    public static final int DOUBLEOBJ_FIELD_NUMBER = 15;
    private java.util.List<java.lang.Double> doubleObj_;
    /**
     * <code>repeated double doubleObj = 15 [packed = true];</code>
     *
     * <pre>
     * </pre>
     */
    public java.util.List<java.lang.Double>
        getDoubleObjList() {
      return doubleObj_;
    }
    /**
     * <code>repeated double doubleObj = 15 [packed = true];</code>
     *
     * <pre>
     * </pre>
     */
    public int getDoubleObjCount() {
      return doubleObj_.size();
    }
    /**
     * <code>repeated double doubleObj = 15 [packed = true];</code>
     *
     * <pre>
     * </pre>
     */
    public double getDoubleObj(int index) {
      return doubleObj_.get(index);
    }
    private int doubleObjMemoizedSerializedSize = -1;

    public static final int INNERMESSAGE_FIELD_NUMBER = 16;
    private com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessage innerMessage_;
    /**
     * <code>optional .com.whollyframework.protobuf.InnerMessage innerMessage = 16;</code>
     */
    public boolean hasInnerMessage() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    /**
     * <code>optional .com.whollyframework.protobuf.InnerMessage innerMessage = 16;</code>
     */
    public com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessage getInnerMessage() {
      return innerMessage_;
    }
    /**
     * <code>optional .com.whollyframework.protobuf.InnerMessage innerMessage = 16;</code>
     */
    public com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessageOrBuilder getInnerMessageOrBuilder() {
      return innerMessage_;
    }

    private void initFields() {
      strObj_ = "hello";
      int32Obj_ = 0;
      int64Obj_ = 0L;
      uint32Obj_ = 0;
      uint64Obj_ = 0L;
      sint32Obj_ = 0;
      sint64Obj_ = 0L;
      fixed32Obj_ = 0;
      fixed64Obj_ = 0L;
      sfixed32Obj_ = 0;
      sfixed64Obj_ = 0L;
      boolObj_ = false;
      bytesObj_ = com.google.protobuf.ByteString.EMPTY;
      folatObj_ = 0F;
      doubleObj_ = java.util.Collections.emptyList();
      innerMessage_ = com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessage.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasStrObj()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getStrObjBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, int32Obj_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, int64Obj_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, uint32Obj_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt64(5, uint64Obj_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeSInt32(6, sint32Obj_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeSInt64(7, sint64Obj_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeFixed32(8, fixed32Obj_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeFixed64(9, fixed64Obj_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeSFixed32(10, sfixed32Obj_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeSFixed64(11, sfixed64Obj_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeBool(12, boolObj_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeBytes(13, bytesObj_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeFloat(14, folatObj_);
      }
      if (getDoubleObjList().size() > 0) {
        output.writeRawVarint32(122);
        output.writeRawVarint32(doubleObjMemoizedSerializedSize);
      }
      for (int i = 0; i < doubleObj_.size(); i++) {
        output.writeDoubleNoTag(doubleObj_.get(i));
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeMessage(16, innerMessage_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getStrObjBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, int32Obj_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, int64Obj_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, uint32Obj_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, uint64Obj_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(6, sint32Obj_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(7, sint64Obj_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(8, fixed32Obj_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(9, fixed64Obj_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSFixed32Size(10, sfixed32Obj_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSFixed64Size(11, sfixed64Obj_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(12, boolObj_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(13, bytesObj_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(14, folatObj_);
      }
      {
        int dataSize = 0;
        dataSize = 8 * getDoubleObjList().size();
        size += dataSize;
        if (!getDoubleObjList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        doubleObjMemoizedSerializedSize = dataSize;
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(16, innerMessage_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.whollyframework.protobuf.model.MessageProtos.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.whollyframework.protobuf.model.MessageProtos.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.whollyframework.protobuf.model.MessageProtos.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.whollyframework.protobuf.model.MessageProtos.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.whollyframework.protobuf.model.MessageProtos.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.whollyframework.protobuf.model.MessageProtos.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.whollyframework.protobuf.model.MessageProtos.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.whollyframework.protobuf.model.MessageProtos.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.whollyframework.protobuf.model.MessageProtos.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.whollyframework.protobuf.model.MessageProtos.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.whollyframework.protobuf.model.MessageProtos.Message prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.whollyframework.protobuf.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.whollyframework.protobuf.Message)
        com.whollyframework.protobuf.model.MessageProtos.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.whollyframework.protobuf.model.MessageProtos.internal_static_com_whollyframework_protobuf_Message_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.whollyframework.protobuf.model.MessageProtos.internal_static_com_whollyframework_protobuf_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.whollyframework.protobuf.model.MessageProtos.Message.class, com.whollyframework.protobuf.model.MessageProtos.Message.Builder.class);
      }

      // Construct using com.whollyframework.protobuf.model.MessageProtos.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getInnerMessageFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        strObj_ = "hello";
        bitField0_ = (bitField0_ & ~0x00000001);
        int32Obj_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        int64Obj_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        uint32Obj_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        uint64Obj_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        sint32Obj_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        sint64Obj_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000040);
        fixed32Obj_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        fixed64Obj_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000100);
        sfixed32Obj_ = 0;
        bitField0_ = (bitField0_ & ~0x00000200);
        sfixed64Obj_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000400);
        boolObj_ = false;
        bitField0_ = (bitField0_ & ~0x00000800);
        bytesObj_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00001000);
        folatObj_ = 0F;
        bitField0_ = (bitField0_ & ~0x00002000);
        doubleObj_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00004000);
        if (innerMessageBuilder_ == null) {
          innerMessage_ = com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessage.getDefaultInstance();
        } else {
          innerMessageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00008000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.whollyframework.protobuf.model.MessageProtos.internal_static_com_whollyframework_protobuf_Message_descriptor;
      }

      public com.whollyframework.protobuf.model.MessageProtos.Message getDefaultInstanceForType() {
        return com.whollyframework.protobuf.model.MessageProtos.Message.getDefaultInstance();
      }

      public com.whollyframework.protobuf.model.MessageProtos.Message build() {
        com.whollyframework.protobuf.model.MessageProtos.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.whollyframework.protobuf.model.MessageProtos.Message buildPartial() {
        com.whollyframework.protobuf.model.MessageProtos.Message result = new com.whollyframework.protobuf.model.MessageProtos.Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.strObj_ = strObj_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.int32Obj_ = int32Obj_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.int64Obj_ = int64Obj_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.uint32Obj_ = uint32Obj_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.uint64Obj_ = uint64Obj_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.sint32Obj_ = sint32Obj_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.sint64Obj_ = sint64Obj_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.fixed32Obj_ = fixed32Obj_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.fixed64Obj_ = fixed64Obj_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.sfixed32Obj_ = sfixed32Obj_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.sfixed64Obj_ = sfixed64Obj_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.boolObj_ = boolObj_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.bytesObj_ = bytesObj_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.folatObj_ = folatObj_;
        if (((bitField0_ & 0x00004000) == 0x00004000)) {
          doubleObj_ = java.util.Collections.unmodifiableList(doubleObj_);
          bitField0_ = (bitField0_ & ~0x00004000);
        }
        result.doubleObj_ = doubleObj_;
        if (((from_bitField0_ & 0x00008000) == 0x00008000)) {
          to_bitField0_ |= 0x00004000;
        }
        if (innerMessageBuilder_ == null) {
          result.innerMessage_ = innerMessage_;
        } else {
          result.innerMessage_ = innerMessageBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.whollyframework.protobuf.model.MessageProtos.Message) {
          return mergeFrom((com.whollyframework.protobuf.model.MessageProtos.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.whollyframework.protobuf.model.MessageProtos.Message other) {
        if (other == com.whollyframework.protobuf.model.MessageProtos.Message.getDefaultInstance()) return this;
        if (other.hasStrObj()) {
          bitField0_ |= 0x00000001;
          strObj_ = other.strObj_;
          onChanged();
        }
        if (other.hasInt32Obj()) {
          setInt32Obj(other.getInt32Obj());
        }
        if (other.hasInt64Obj()) {
          setInt64Obj(other.getInt64Obj());
        }
        if (other.hasUint32Obj()) {
          setUint32Obj(other.getUint32Obj());
        }
        if (other.hasUint64Obj()) {
          setUint64Obj(other.getUint64Obj());
        }
        if (other.hasSint32Obj()) {
          setSint32Obj(other.getSint32Obj());
        }
        if (other.hasSint64Obj()) {
          setSint64Obj(other.getSint64Obj());
        }
        if (other.hasFixed32Obj()) {
          setFixed32Obj(other.getFixed32Obj());
        }
        if (other.hasFixed64Obj()) {
          setFixed64Obj(other.getFixed64Obj());
        }
        if (other.hasSfixed32Obj()) {
          setSfixed32Obj(other.getSfixed32Obj());
        }
        if (other.hasSfixed64Obj()) {
          setSfixed64Obj(other.getSfixed64Obj());
        }
        if (other.hasBoolObj()) {
          setBoolObj(other.getBoolObj());
        }
        if (other.hasBytesObj()) {
          setBytesObj(other.getBytesObj());
        }
        if (other.hasFolatObj()) {
          setFolatObj(other.getFolatObj());
        }
        if (!other.doubleObj_.isEmpty()) {
          if (doubleObj_.isEmpty()) {
            doubleObj_ = other.doubleObj_;
            bitField0_ = (bitField0_ & ~0x00004000);
          } else {
            ensureDoubleObjIsMutable();
            doubleObj_.addAll(other.doubleObj_);
          }
          onChanged();
        }
        if (other.hasInnerMessage()) {
          mergeInnerMessage(other.getInnerMessage());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasStrObj()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.whollyframework.protobuf.model.MessageProtos.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.whollyframework.protobuf.model.MessageProtos.Message) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object strObj_ = "hello";
      /**
       * <code>required string strObj = 1 [default = "hello"];</code>
       */
      public boolean hasStrObj() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string strObj = 1 [default = "hello"];</code>
       */
      public java.lang.String getStrObj() {
        java.lang.Object ref = strObj_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            strObj_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string strObj = 1 [default = "hello"];</code>
       */
      public com.google.protobuf.ByteString
          getStrObjBytes() {
        java.lang.Object ref = strObj_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          strObj_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string strObj = 1 [default = "hello"];</code>
       */
      public Builder setStrObj(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        strObj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string strObj = 1 [default = "hello"];</code>
       */
      public Builder clearStrObj() {
        bitField0_ = (bitField0_ & ~0x00000001);
        strObj_ = getDefaultInstance().getStrObj();
        onChanged();
        return this;
      }
      /**
       * <code>required string strObj = 1 [default = "hello"];</code>
       */
      public Builder setStrObjBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        strObj_ = value;
        onChanged();
        return this;
      }

      private int int32Obj_ ;
      /**
       * <code>optional int32 int32Obj = 2;</code>
       */
      public boolean hasInt32Obj() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 int32Obj = 2;</code>
       */
      public int getInt32Obj() {
        return int32Obj_;
      }
      /**
       * <code>optional int32 int32Obj = 2;</code>
       */
      public Builder setInt32Obj(int value) {
        bitField0_ |= 0x00000002;
        int32Obj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 int32Obj = 2;</code>
       */
      public Builder clearInt32Obj() {
        bitField0_ = (bitField0_ & ~0x00000002);
        int32Obj_ = 0;
        onChanged();
        return this;
      }

      private long int64Obj_ ;
      /**
       * <code>optional int64 int64Obj = 3;</code>
       */
      public boolean hasInt64Obj() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 int64Obj = 3;</code>
       */
      public long getInt64Obj() {
        return int64Obj_;
      }
      /**
       * <code>optional int64 int64Obj = 3;</code>
       */
      public Builder setInt64Obj(long value) {
        bitField0_ |= 0x00000004;
        int64Obj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 int64Obj = 3;</code>
       */
      public Builder clearInt64Obj() {
        bitField0_ = (bitField0_ & ~0x00000004);
        int64Obj_ = 0L;
        onChanged();
        return this;
      }

      private int uint32Obj_ ;
      /**
       * <code>optional uint32 uint32Obj = 4;</code>
       */
      public boolean hasUint32Obj() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional uint32 uint32Obj = 4;</code>
       */
      public int getUint32Obj() {
        return uint32Obj_;
      }
      /**
       * <code>optional uint32 uint32Obj = 4;</code>
       */
      public Builder setUint32Obj(int value) {
        bitField0_ |= 0x00000008;
        uint32Obj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 uint32Obj = 4;</code>
       */
      public Builder clearUint32Obj() {
        bitField0_ = (bitField0_ & ~0x00000008);
        uint32Obj_ = 0;
        onChanged();
        return this;
      }

      private long uint64Obj_ ;
      /**
       * <code>optional uint64 uint64Obj = 5;</code>
       */
      public boolean hasUint64Obj() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional uint64 uint64Obj = 5;</code>
       */
      public long getUint64Obj() {
        return uint64Obj_;
      }
      /**
       * <code>optional uint64 uint64Obj = 5;</code>
       */
      public Builder setUint64Obj(long value) {
        bitField0_ |= 0x00000010;
        uint64Obj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 uint64Obj = 5;</code>
       */
      public Builder clearUint64Obj() {
        bitField0_ = (bitField0_ & ~0x00000010);
        uint64Obj_ = 0L;
        onChanged();
        return this;
      }

      private int sint32Obj_ ;
      /**
       * <code>optional sint32 sint32Obj = 6;</code>
       */
      public boolean hasSint32Obj() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional sint32 sint32Obj = 6;</code>
       */
      public int getSint32Obj() {
        return sint32Obj_;
      }
      /**
       * <code>optional sint32 sint32Obj = 6;</code>
       */
      public Builder setSint32Obj(int value) {
        bitField0_ |= 0x00000020;
        sint32Obj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint32 sint32Obj = 6;</code>
       */
      public Builder clearSint32Obj() {
        bitField0_ = (bitField0_ & ~0x00000020);
        sint32Obj_ = 0;
        onChanged();
        return this;
      }

      private long sint64Obj_ ;
      /**
       * <code>optional sint64 sint64Obj = 7;</code>
       */
      public boolean hasSint64Obj() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional sint64 sint64Obj = 7;</code>
       */
      public long getSint64Obj() {
        return sint64Obj_;
      }
      /**
       * <code>optional sint64 sint64Obj = 7;</code>
       */
      public Builder setSint64Obj(long value) {
        bitField0_ |= 0x00000040;
        sint64Obj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint64 sint64Obj = 7;</code>
       */
      public Builder clearSint64Obj() {
        bitField0_ = (bitField0_ & ~0x00000040);
        sint64Obj_ = 0L;
        onChanged();
        return this;
      }

      private int fixed32Obj_ ;
      /**
       * <code>optional fixed32 fixed32Obj = 8;</code>
       */
      public boolean hasFixed32Obj() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional fixed32 fixed32Obj = 8;</code>
       */
      public int getFixed32Obj() {
        return fixed32Obj_;
      }
      /**
       * <code>optional fixed32 fixed32Obj = 8;</code>
       */
      public Builder setFixed32Obj(int value) {
        bitField0_ |= 0x00000080;
        fixed32Obj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional fixed32 fixed32Obj = 8;</code>
       */
      public Builder clearFixed32Obj() {
        bitField0_ = (bitField0_ & ~0x00000080);
        fixed32Obj_ = 0;
        onChanged();
        return this;
      }

      private long fixed64Obj_ ;
      /**
       * <code>optional fixed64 fixed64Obj = 9;</code>
       */
      public boolean hasFixed64Obj() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional fixed64 fixed64Obj = 9;</code>
       */
      public long getFixed64Obj() {
        return fixed64Obj_;
      }
      /**
       * <code>optional fixed64 fixed64Obj = 9;</code>
       */
      public Builder setFixed64Obj(long value) {
        bitField0_ |= 0x00000100;
        fixed64Obj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional fixed64 fixed64Obj = 9;</code>
       */
      public Builder clearFixed64Obj() {
        bitField0_ = (bitField0_ & ~0x00000100);
        fixed64Obj_ = 0L;
        onChanged();
        return this;
      }

      private int sfixed32Obj_ ;
      /**
       * <code>optional sfixed32 sfixed32Obj = 10;</code>
       */
      public boolean hasSfixed32Obj() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional sfixed32 sfixed32Obj = 10;</code>
       */
      public int getSfixed32Obj() {
        return sfixed32Obj_;
      }
      /**
       * <code>optional sfixed32 sfixed32Obj = 10;</code>
       */
      public Builder setSfixed32Obj(int value) {
        bitField0_ |= 0x00000200;
        sfixed32Obj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sfixed32 sfixed32Obj = 10;</code>
       */
      public Builder clearSfixed32Obj() {
        bitField0_ = (bitField0_ & ~0x00000200);
        sfixed32Obj_ = 0;
        onChanged();
        return this;
      }

      private long sfixed64Obj_ ;
      /**
       * <code>optional sfixed64 sfixed64Obj = 11;</code>
       */
      public boolean hasSfixed64Obj() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional sfixed64 sfixed64Obj = 11;</code>
       */
      public long getSfixed64Obj() {
        return sfixed64Obj_;
      }
      /**
       * <code>optional sfixed64 sfixed64Obj = 11;</code>
       */
      public Builder setSfixed64Obj(long value) {
        bitField0_ |= 0x00000400;
        sfixed64Obj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sfixed64 sfixed64Obj = 11;</code>
       */
      public Builder clearSfixed64Obj() {
        bitField0_ = (bitField0_ & ~0x00000400);
        sfixed64Obj_ = 0L;
        onChanged();
        return this;
      }

      private boolean boolObj_ ;
      /**
       * <code>optional bool boolObj = 12;</code>
       */
      public boolean hasBoolObj() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional bool boolObj = 12;</code>
       */
      public boolean getBoolObj() {
        return boolObj_;
      }
      /**
       * <code>optional bool boolObj = 12;</code>
       */
      public Builder setBoolObj(boolean value) {
        bitField0_ |= 0x00000800;
        boolObj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool boolObj = 12;</code>
       */
      public Builder clearBoolObj() {
        bitField0_ = (bitField0_ & ~0x00000800);
        boolObj_ = false;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString bytesObj_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes bytesObj = 13;</code>
       */
      public boolean hasBytesObj() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>optional bytes bytesObj = 13;</code>
       */
      public com.google.protobuf.ByteString getBytesObj() {
        return bytesObj_;
      }
      /**
       * <code>optional bytes bytesObj = 13;</code>
       */
      public Builder setBytesObj(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        bytesObj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes bytesObj = 13;</code>
       */
      public Builder clearBytesObj() {
        bitField0_ = (bitField0_ & ~0x00001000);
        bytesObj_ = getDefaultInstance().getBytesObj();
        onChanged();
        return this;
      }

      private float folatObj_ ;
      /**
       * <code>optional float folatObj = 14 [deprecated = true];</code>
       */
      @java.lang.Deprecated public boolean hasFolatObj() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      /**
       * <code>optional float folatObj = 14 [deprecated = true];</code>
       */
      @java.lang.Deprecated public float getFolatObj() {
        return folatObj_;
      }
      /**
       * <code>optional float folatObj = 14 [deprecated = true];</code>
       */
      @java.lang.Deprecated public Builder setFolatObj(float value) {
        bitField0_ |= 0x00002000;
        folatObj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float folatObj = 14 [deprecated = true];</code>
       */
      @java.lang.Deprecated public Builder clearFolatObj() {
        bitField0_ = (bitField0_ & ~0x00002000);
        folatObj_ = 0F;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Double> doubleObj_ = java.util.Collections.emptyList();
      private void ensureDoubleObjIsMutable() {
        if (!((bitField0_ & 0x00004000) == 0x00004000)) {
          doubleObj_ = new java.util.ArrayList<java.lang.Double>(doubleObj_);
          bitField0_ |= 0x00004000;
         }
      }
      /**
       * <code>repeated double doubleObj = 15 [packed = true];</code>
       *
       * <pre>
       * </pre>
       */
      public java.util.List<java.lang.Double>
          getDoubleObjList() {
        return java.util.Collections.unmodifiableList(doubleObj_);
      }
      /**
       * <code>repeated double doubleObj = 15 [packed = true];</code>
       *
       * <pre>
       * </pre>
       */
      public int getDoubleObjCount() {
        return doubleObj_.size();
      }
      /**
       * <code>repeated double doubleObj = 15 [packed = true];</code>
       *
       * <pre>
       * </pre>
       */
      public double getDoubleObj(int index) {
        return doubleObj_.get(index);
      }
      /**
       * <code>repeated double doubleObj = 15 [packed = true];</code>
       *
       * <pre>
       * </pre>
       */
      public Builder setDoubleObj(
          int index, double value) {
        ensureDoubleObjIsMutable();
        doubleObj_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double doubleObj = 15 [packed = true];</code>
       *
       * <pre>
       * </pre>
       */
      public Builder addDoubleObj(double value) {
        ensureDoubleObjIsMutable();
        doubleObj_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double doubleObj = 15 [packed = true];</code>
       *
       * <pre>
       * </pre>
       */
      public Builder addAllDoubleObj(
          java.lang.Iterable<? extends java.lang.Double> values) {
        ensureDoubleObjIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, doubleObj_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double doubleObj = 15 [packed = true];</code>
       *
       * <pre>
       * </pre>
       */
      public Builder clearDoubleObj() {
        doubleObj_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00004000);
        onChanged();
        return this;
      }

      private com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessage innerMessage_ = com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessage.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessage, com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessage.Builder, com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessageOrBuilder> innerMessageBuilder_;
      /**
       * <code>optional .com.whollyframework.protobuf.InnerMessage innerMessage = 16;</code>
       */
      public boolean hasInnerMessage() {
        return ((bitField0_ & 0x00008000) == 0x00008000);
      }
      /**
       * <code>optional .com.whollyframework.protobuf.InnerMessage innerMessage = 16;</code>
       */
      public com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessage getInnerMessage() {
        if (innerMessageBuilder_ == null) {
          return innerMessage_;
        } else {
          return innerMessageBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.whollyframework.protobuf.InnerMessage innerMessage = 16;</code>
       */
      public Builder setInnerMessage(com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessage value) {
        if (innerMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          innerMessage_ = value;
          onChanged();
        } else {
          innerMessageBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00008000;
        return this;
      }
      /**
       * <code>optional .com.whollyframework.protobuf.InnerMessage innerMessage = 16;</code>
       */
      public Builder setInnerMessage(
          com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessage.Builder builderForValue) {
        if (innerMessageBuilder_ == null) {
          innerMessage_ = builderForValue.build();
          onChanged();
        } else {
          innerMessageBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00008000;
        return this;
      }
      /**
       * <code>optional .com.whollyframework.protobuf.InnerMessage innerMessage = 16;</code>
       */
      public Builder mergeInnerMessage(com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessage value) {
        if (innerMessageBuilder_ == null) {
          if (((bitField0_ & 0x00008000) == 0x00008000) &&
              innerMessage_ != com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessage.getDefaultInstance()) {
            innerMessage_ =
              com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessage.newBuilder(innerMessage_).mergeFrom(value).buildPartial();
          } else {
            innerMessage_ = value;
          }
          onChanged();
        } else {
          innerMessageBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00008000;
        return this;
      }
      /**
       * <code>optional .com.whollyframework.protobuf.InnerMessage innerMessage = 16;</code>
       */
      public Builder clearInnerMessage() {
        if (innerMessageBuilder_ == null) {
          innerMessage_ = com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessage.getDefaultInstance();
          onChanged();
        } else {
          innerMessageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00008000);
        return this;
      }
      /**
       * <code>optional .com.whollyframework.protobuf.InnerMessage innerMessage = 16;</code>
       */
      public com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessage.Builder getInnerMessageBuilder() {
        bitField0_ |= 0x00008000;
        onChanged();
        return getInnerMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.whollyframework.protobuf.InnerMessage innerMessage = 16;</code>
       */
      public com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessageOrBuilder getInnerMessageOrBuilder() {
        if (innerMessageBuilder_ != null) {
          return innerMessageBuilder_.getMessageOrBuilder();
        } else {
          return innerMessage_;
        }
      }
      /**
       * <code>optional .com.whollyframework.protobuf.InnerMessage innerMessage = 16;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessage, com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessage.Builder, com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessageOrBuilder> 
          getInnerMessageFieldBuilder() {
        if (innerMessageBuilder_ == null) {
          innerMessageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessage, com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessage.Builder, com.whollyframework.protobuf.model.InnerMessageProtos.InnerMessageOrBuilder>(
                  getInnerMessage(),
                  getParentForChildren(),
                  isClean());
          innerMessage_ = null;
        }
        return innerMessageBuilder_;
      }


      public Message buildMessage(MessagePojo msgPojo){
      	
      	MessageProtos.Message.Builder messageBuilder = MessageProtos.Message.newBuilder();

  	      messageBuilder.setStrObj(msgPojo.getStrObj());
  	      messageBuilder.setFolatObj(msgPojo.getFolatObj());
  	    messageBuilder.addAllDoubleObj(msgPojo.getDoubleObj());
  	      messageBuilder.setBoolObj(msgPojo.isBoolObj());

  	      messageBuilder.setBytesObj(ByteString.copyFrom(msgPojo.getBytesObj()));
  	      messageBuilder.setInt32Obj(msgPojo.getInt32Obj());
  	      messageBuilder.setInt64Obj(msgPojo.getInt64Obj());
  	      messageBuilder.setSint32Obj(msgPojo.getSint32Obj());
  	      messageBuilder.setSint64Obj(msgPojo.getSint64Obj());
  	      messageBuilder.setFixed32Obj(msgPojo.getFixed32Obj());
  	      messageBuilder.setFixed64Obj(msgPojo.getFixed64Obj());
  	      messageBuilder.setSfixed32Obj(msgPojo.getSfixed32Obj());
  	      messageBuilder.setSfixed64Obj(msgPojo.getSfixed64Obj());
  	      messageBuilder.setUint32Obj(msgPojo.getUint32Obj());
  	      messageBuilder.setUint64Obj(msgPojo.getUint64Obj());

  	      InnerMessageProtos.InnerMessage.Builder innerMessageBuilder = InnerMessageProtos.InnerMessage.newBuilder();
  	      innerMessageBuilder.setId(msgPojo.getInnerMessage().getId());
  	      innerMessageBuilder.setName(msgPojo.getInnerMessage().getName());
  	      innerMessageBuilder.setType(EnumTypeProtos.EnumType.PRODUCTS);

  	      messageBuilder.setInnerMessage(innerMessageBuilder);

  	      return messageBuilder.build();
      }
      // @@protoc_insertion_point(builder_scope:com.whollyframework.protobuf.Message)
    }

    static {
      defaultInstance = new Message(true);
      defaultInstance.initFields();
    }
    // @@protoc_insertion_point(class_scope:com.whollyframework.protobuf.Message)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_whollyframework_protobuf_Message_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_whollyframework_protobuf_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMessage.proto\022\034com.whollyframework.pro" +
      "tobuf\032\022InnerMessage.proto\"\364\002\n\007Message\022\025\n" +
      "\006strObj\030\001 \002(\t:\005hello\022\020\n\010int32Obj\030\002 \001(\005\022\020" +
      "\n\010int64Obj\030\003 \001(\003\022\021\n\tuint32Obj\030\004 \001(\r\022\021\n\tu" +
      "int64Obj\030\005 \001(\004\022\021\n\tsint32Obj\030\006 \001(\021\022\021\n\tsin" +
      "t64Obj\030\007 \001(\022\022\022\n\nfixed32Obj\030\010 \001(\007\022\022\n\nfixe" +
      "d64Obj\030\t \001(\006\022\023\n\013sfixed32Obj\030\n \001(\017\022\023\n\013sfi" +
      "xed64Obj\030\013 \001(\020\022\017\n\007boolObj\030\014 \001(\010\022\020\n\010bytes" +
      "Obj\030\r \001(\014\022\024\n\010folatObj\030\016 \001(\002B\002\030\001\022\025\n\tdoubl" +
      "eObj\030\017 \003(\001B\002\020\001\022@\n\014innerMessage\030\020 \001(\0132*.c",
      "om.whollyframework.protobuf.InnerMessage" +
      "B8\n\"com.whollyframework.protobuf.modelB\r" +
      "MessageProtosH\001\210\001\000"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.whollyframework.protobuf.model.InnerMessageProtos.getDescriptor(),
        }, assigner);
    internal_static_com_whollyframework_protobuf_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_whollyframework_protobuf_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_whollyframework_protobuf_Message_descriptor,
        new java.lang.String[] { "StrObj", "Int32Obj", "Int64Obj", "Uint32Obj", "Uint64Obj", "Sint32Obj", "Sint64Obj", "Fixed32Obj", "Fixed64Obj", "Sfixed32Obj", "Sfixed64Obj", "BoolObj", "BytesObj", "FolatObj", "DoubleObj", "InnerMessage", });
    com.whollyframework.protobuf.model.InnerMessageProtos.getDescriptor();
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
