DROP TABLE IF EXISTS SYS_CONFIG;

DROP TABLE IF EXISTS SYS_MENU_INFO;

DROP TABLE IF EXISTS SYS_OPERATE_LOG;

DROP TABLE IF EXISTS SYS_ORGANIZATION;

DROP TABLE IF EXISTS SYS_PERMISSION;

DROP TABLE IF EXISTS SYS_ROLE_INFO;

DROP TABLE IF EXISTS SYS_SEQUENCE;

DROP TABLE IF EXISTS SYS_USER_INFO;

DROP TABLE IF EXISTS SYS_USER_BIND_IP;

DROP TABLE IF EXISTS SYS_USER_ROLE_SET;

DROP TABLE IF EXISTS SYS_VERSION;

DROP FUNCTION IF EXISTS _nextval;

DROP FUNCTION IF EXISTS _currval;